authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

market_prj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

import mainapp.views as mainapp

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', mainapp.main, name='main'),
    path('list_of_accommodations/', include('mainapp.urls', namespace='acc')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser


class TravelUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст', default=18)


class TravelUserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'W'

    GENDER_CHOICES = (
        (MALE, 'М'),
        (FEMALE, 'Ж'),
    )

    user = models.OneToOneField(
        TravelUser, unique=True, null=False, db_index=True,
        on_delete=models.CASCADE)
    tagline = models.CharField(
        verbose_name='теги', max_length=128, blank=True)
    aboutMe = models.TextField(
        verbose_name='о себе', max_length=512, blank=True)
    gender = models.CharField(
        verbose_name='пол', max_length=1, choices=GENDER_CHOICES, blank=True)

    @receiver(post_save, sender=TravelUser)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            TravelUserProfile.objects.create(user=instance)

    @receiver(post_save, sender=TravelUser)
    def save_user_profile(sender, instance, **kwargs):
        instance.traveluserprofile.save()

authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm,\
    UserChangeForm, UserCreationForm

from .models import TravelUser, TravelUserProfile


# Формы регистрации пользователя
class TravelUserRegisterForm(UserCreationForm):
    class Meta:
        model = TravelUser
        fields = (
            'username', 'first_name', 'password1',
            'password2', 'email', 'age', 'avatar'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data


# Форма редактирования регистрационных данных пользователя
class TravelUserEditForm(UserChangeForm):
    class Meta:
        model = TravelUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar',
                  'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("ВЫ слишком молоды!")

        return data


# Форма для аутентификации
class TravelUserLoginForm(AuthenticationForm):
    class Meta:
        model = TravelUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(TravelUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


# Форма для редактирования профиля пользователя
class TravelUserProfileEditForm(forms.ModelForm):
    class Meta:
        model = TravelUserProfile
        fields = ('tagline', 'aboutMe', 'gender')

    def __init__(self, *args, **kwargs):
        super(TravelUserProfileEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

authapp/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth
from django.db import transaction
from authapp.forms import TravelUserRegisterForm, TravelUserLoginForm, \
    TravelUserEditForm, TravelUserProfileEditForm


# Регистрация пользователя
def register(request):

    title = 'регистрация'

    if request.method == 'POST':
        register_form = TravelUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = TravelUserRegisterForm()

    content = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', content)


# Аутентификация пользователя
def login(request):
    title = 'вход'

    login_form = TravelUserLoginForm(data=request.POST or None)

    next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():

        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('main'))

    content = {
        'title': title,
        'login_form': login_form,
        'next': next,
    }

    return render(request, 'authapp/login.html', content)


# Завершение сессии
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


# Редактирование данных пользователя и его профиля
@transaction.atomic()
def edit(request):

    title = 'редактирование'

    if request.method == 'POST':
        edit_form = TravelUserEditForm(request.POST,
                                       request.FILES, instance=request.user)
        profile_form = TravelUserProfileEditForm(
            request.POST, instance=request.user.traveluserprofile)

        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = TravelUserEditForm(instance=request.user)
        profile_form = TravelUserProfileEditForm(instance=
                                                 request.user.traveluserprofile)

    content = {'title': title,
               'edit_form': edit_form,
               'profile_form': profile_form}

    return render(request, 'authapp/edit.html', content)

authapp/templates/authapp/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block title %}
        <title>TravelMarket</title>
    {% endblock %}
    {% block css %}
        <link rel="stylesheet" type="text/css"
              href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css"
              href="{% static 'css/style.css' %}">
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
              crossorigin="anonymous">
    {% endblock %}
    {% block js %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
                integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
                crossorigin="anonymous"></script>
    {% endblock %}


</head>
<body>
<div class="container">

    {% block menu %}
        {% include 'mainapp/includes/inc_menu.html' %}
    {% endblock %}

    {% block list %}

    {% endblock %}

    {% block content %}

    {% endblock %}

</div>
</body>
<footer>
    {% block footer %}
        {% include 'mainapp/includes/inc_footer.html' %}
    {% endblock %}
</footer>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <div class="container form-group row">
        <div class="user_avatar float-right">
            <img src="/media/{{ user.avatar|default:'users_avatars/default.jpg' }}">
        </div>
        <div>
            <form class="col-lg-offset-4  form-horizontal "
                  action="{% url 'auth:edit' %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ edit_form.as_p }}
                {{ profile_form.as_p }}
                <input class="form-control btn btn-outline-success"
                       type="submit" value="сохранить">

                <button class="btn btn-outline-warning
                form-control col-lg-offset-4 last">
                    <a style="color: black; text-decoration: none"
                       href="{% url 'main' %}" class="">
                        на главную
                    </a>
                </button>
            </form>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="login">
            <div class="h2 text-center head">Вход в систему</div>

            <form class="form-horizontal"
                  action="{% url 'auth:login' %}" method="post">
                {% csrf_token %}
                {% if next %}
                    <input type="hidden" name="next" value="{{ next }}">
                {% endif %}
                {{ login_form.as_p }}
                <br>
                <input class="form-control" type="submit" value="войти">
            </form>
            <button class="btn btn-round form-control">
                <a href="{% url 'auth:register' %}" class="">
                    зарегистрироваться
                </a>
            </button>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Регистрация нового пользователя
            </div>
            <form class="form-horizontal"
                  action="{% url 'auth:register' %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ register_form.as_p }}
                <br>
                <input class="form-control" type="submit" value="зарегистрироваться">
            </form>
        </div>
    </div>
{% endblock %}